### ISSUE TITLE
not working with TB 58.0b2 (32-bit) nor 59.0a1 (2017-12-28) (64-bit)

### ISSUE THREAD

**Issue by n8v8R** [jobisoft/TbSync#27]
tested with both on W10 x64 (b16299). The TbSync account manager windows opens but clicking on the + icon does nothing, i.e. no accounts can be added

**Comment by jobisoft** [comment]
Can you retry with the latest beta [TbSync v0.6.8.3 (2017.12.28)](https://github.com/jobisoft/TbSync/releases/download/v0.6.8.2/TbSync-0.6.8.3-2017.12.28.xpi) ?

**Comment by n8v8R** [comment]
thanks for the beta, but unfortunately no deal on either TB version. From the error console:
```
NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIXPCComponents_Utils.import]  accountManager.js:4
	<anonymous> chrome://tbsync/content/accountManager.js:4:1
TypeError: tbSyncAccountManager is undefined[Learn More]  accountManager.xul:1:1
	onload chrome://tbsync/content/accountManager.xul:1:1
```

And there seems to be one more issue - the TbSync account manager _windows_ opens only one time (or in some case not at all). Once closed and tried to be opened again it does not. Nothing in the error console though.

**Comment by jobisoft** [comment]
Confirmed. If you remove this [line](https://github.com/jobisoft/TbSync/blob/master/content/accountManager.js#L4) it works again (honestly I do not remember, why I include that file).

However, there are also some changes with Lightning 6, now I get

`cal.makeURL is not a function" {file: "chrome://tbsync/content/tbsync.jsm" line: 836`

...

**Comment by jobisoft** [comment]
And obviously I can no longer use the double click on the status bar to open the account manager...

**Comment by jobisoft** [comment]
fixed

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
